Repository JobITs-DSM/Benecia, pull requests merged in 2021-12, with the labels that each got.

#77 ExceptionHandler 추가
  build.gradle
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/BusinessAreaCode.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/EnterpriseDivisionCode.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/EnterpriseEmployeeCountCode.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/HiringArea.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/ProgrammingLanguageCode.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/RecruitmentFullTimePayCode.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/RecruitmentReportingTimeCode.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/RecruitmentStatusCode.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/ScreeningProcessCode.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/TechnologyCode.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/WelfareCode.java
  src/main/java/com/jobits/dsm/benecia/global/error/ErrorAttribute.java
  src/main/java/com/jobits/dsm/benecia/global/error/GlobalErrorCode.java
  src/main/java/com/jobits/dsm/benecia/global/error/exception/AttributeConvertFailedException.java
  src/main/java/com/jobits/dsm/benecia/global/error/exception/BadRequestException.java
  src/main/java/com/jobits/dsm/benecia/global/error/exception/GlobalException.java
  src/main/java/com/jobits/dsm/benecia/global/error/exception/NotFoundException.java
  src/main/java/com/jobits/dsm/benecia/global/error/exception/UnexpectedException.java
  src/main/java/com/jobits/dsm/benecia/global/error/handler/ErrorResponse.java
  src/main/java/com/jobits/dsm/benecia/global/error/handler/ExceptionHandlerFilter.java
  src/main/java/com/jobits/dsm/benecia/global/exception/AttributeConvertFailedException.java
  src/main/java/com/jobits/dsm/benecia/global/security/FilterConfig.java
  src/main/java/com/jobits/dsm/benecia/global/security/SecurityConfig.java
Labels: enhancement

#80 #79 프로젝트 폴더 구조 세팅
  src/main/java/com/jobits/dsm/benecia/domain/application/code/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/application/domain/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/application/exceptions/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/application/presentation/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/application/presentation/payload/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/application/service/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/attatchment/code/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/attatchment/domain/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/attatchment/exceptions/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/attatchment/presentation/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/attatchment/presentation/payload/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/attatchment/service/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/contract/code/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/contract/domain/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/contract/exceptions/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/contract/presentation/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/contract/presentation/payload/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/contract/service/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/exceptions/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/exceptions/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/review/code/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/review/domain/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/review/exceptions/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/review/presentation/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/review/presentation/payload/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/review/service/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/student/domain/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/student/exceptions/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/student/presentation/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/student/presentation/payload/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/student/service/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/training/code/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/training/domain/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/training/exceptions/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/training/presentation/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/training/presentation/payload/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/training/service/.gitkeep
  src/main/java/com/jobits/dsm/benecia/global/security/auth/.gitkeep
  src/main/java/com/jobits/dsm/benecia/global/security/jwt/.gitkeep
  src/main/java/com/jobits/dsm/benecia/infrastructure/.gitkeep
Labels: setting

#81 Student Enttity / Repository 추가
  src/main/java/com/jobits/dsm/benecia/domain/student/domain/Student.java
  src/main/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepository.java
Labels: enhancement

#92 #91 Review Code 추가
  src/main/java/com/jobits/dsm/benecia/domain/review/code/ReviewCode.java
Labels: enhancement

#87 근로계약 Entity 추가
  src/main/java/com/jobits/dsm/benecia/domain/contract/domain/Contract.java
  src/main/java/com/jobits/dsm/benecia/domain/contract/domain/ContractRepository.java
  src/test/java/com/jobits/dsm/benecia/domain/contract/ContractRepositoryTest.java
Labels: enhancement

#89 현장 실습 엔티티 추가
  src/main/java/com/jobits/dsm/benecia/domain/training/domain/Training.java
  src/main/java/com/jobits/dsm/benecia/domain/training/domain/TrainingRepository.java
  src/test/java/com/jobits/dsm/benecia/domain/training/domain/TraningRepositoryTest.java
Labels: enhancement

#93 #90 Review entity 추가
  src/main/java/com/jobits/dsm/benecia/domain/review/domain/Review.java
  src/main/java/com/jobits/dsm/benecia/domain/review/domain/ReviewRepository.java
  src/test/java/com/jobits/dsm/benecia/domain/review/domain/ReviewRepositoryTest.java
Labels: enhancement

#97 #96 채용 분야 엔티티 추가
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/HiringAreaCode.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/hiringarea/HiringArea.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/hiringarea/HiringAreaRepository.java
  src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/HiringRepositoryTest.java
Labels: enhancement

#99 #98 전형절차 엔티티 추가
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/screeningprocess/ScreeningProcess.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/screeningprocess/ScreeningProcessRepository.java
  src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/ScreeningProcessRepositoryTest.java
Labels: enhancement

#102 #101 복리후생 엔티티 추가
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/welfare/Welfare.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/welfare/WelfareRepository.java
  src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/WelfareRepositoryTest.java
Labels: enhancement

#104 #103 technology entity
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/technology/Technology.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/technology/TechnologyRepository.java
  src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/TechnologyRepositoryTest.java
Labels: enhancement

#108 #95 Application Code 추가
  src/main/java/com/jobits/dsm/benecia/domain/application/code/ApplicationCode.java
Labels: enhancement

#106 #105 첨부파일 엔티티 추가
  src/main/java/com/jobits/dsm/benecia/domain/attatchment/domain/Attachment.java
  src/main/java/com/jobits/dsm/benecia/domain/attatchment/domain/AttachmentRepository.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/Enterprise.java
  src/test/java/com/jobits/dsm/benecia/domain/attachment/domain/AttachmentRepositoryTest.java
Labels: enhancement

#84 #83 student entity test 추가
  build.gradle
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/Recruitment.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentId.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepository.java
  src/main/java/com/jobits/dsm/benecia/domain/student/domain/.gitkeep
  src/main/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepository.java
  src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepositoryTest.java
Labels: test

#110 #94 지원 엔티티 추가
  src/main/java/com/jobits/dsm/benecia/BeneciaApplication.java
  src/main/java/com/jobits/dsm/benecia/domain/application/domain/Application.java
  src/main/java/com/jobits/dsm/benecia/domain/application/domain/ApplicationRepository.java
  src/main/java/com/jobits/dsm/benecia/domain/student/domain/Student.java
Labels: enhancement

#116 #115 필요 언어 API
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/EnterpriseCodeController.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseCodeService.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentCodeController.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentCodeService.java
  src/main/java/com/jobits/dsm/benecia/global/code/CodeResponse.java
Labels: enhancement

#118 #117 복리후생 코드 API
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentCodeController.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentCodeService.java
Labels: enhancement

#120 #119 모집의뢰 코드 목록 API들
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentCodeController.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentCodeService.java
Labels: enhancement

#122 기업 등록 API
  build.gradle
  docs/Benecia.postman_collection.json
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/Address.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/Director.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/Enterprise.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/EnterpriseController.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/request/RegisterEnterpriseRequest.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseService.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentCodeController.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/HiringAreaCodeResponse.java
  src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentCodeService.java
  src/main/java/com/jobits/dsm/benecia/global/error/handler/ErrorResponse.java
  src/main/java/com/jobits/dsm/benecia/global/security/SecurityConfig.java
  src/main/java/com/jobits/dsm/benecia/infrastructure/s3/AmazonS3Config.java
  src/main/java/com/jobits/dsm/benecia/infrastructure/s3/S3Util.java
  src/main/resources/application.yml
  src/test/java/com/jobits/dsm/benecia/domain/enterprise/domain/EnterpriseRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseServiceTest.java
  src/test/resources/application.yml
Labels: enhancement

#130 Redis 설정 추가
  build.gradle
  src/main/java/com/jobits/dsm/benecia/infrastructure/redis/EmbeddedRedisConfig.java
  src/main/java/com/jobits/dsm/benecia/infrastructure/redis/RedisConfig.java
  src/main/java/com/jobits/dsm/benecia/infrastructure/redis/RedisProperty.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: setting

#131 127 기업 등록시 사업분야 추가 등록
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/Enterprise.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/businessarea/BusinessArea.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/businessarea/BusinessAreaRepository.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseService.java
Labels: bug

#132 #124 기업 로그인 추가
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/cache/EnterpriseRefreshToken.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/cache/EnterpriseRefreshTokenRepository.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/exceptions/EnterpriseErrorCode.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/exceptions/EnterpriseNotFoundException.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/EnterpriseController.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/request/EnterpriseSignInRequest.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/response/EnterpriseTokenResponse.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseService.java
  src/main/java/com/jobits/dsm/benecia/global/security/SecurityConfig.java
Labels: enhancement

#133 기업 목록 API
  build.gradle
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/Enterprise.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/EnterpriseRepository.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/EnterpriseRepositoryCustom.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/EnterpriseRepositoryCustomImpl.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/businessarea/BusinessArea.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/EnterpriseController.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/response/EnterpriseListResponse.java
  src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseService.java
  src/main/java/com/jobits/dsm/benecia/domain/review/domain/Review.java
  src/main/java/com/jobits/dsm/benecia/global/error/handler/ExceptionHandlerFilter.java
  src/main/java/com/jobits/dsm/benecia/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/jobits/dsm/benecia/global/security/property/JwtProperty.java
  src/main/java/com/jobits/dsm/benecia/infrastructure/querydsl/QuerydslConfig.java
  src/main/java/com/jobits/dsm/benecia/infrastructure/redis/EmbeddedRedisConfig.java
  src/test/java/com/jobits/dsm/benecia/domain/attachment/domain/AttachmentRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/contract/ContractRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/enterprise/domain/EnterpriseRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/enterprise/domain/ProgrammingLanguageTest.java
  src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/HiringRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/ScreeningProcessRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/TechnologyRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/WelfareRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/review/domain/ReviewRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepositoryTest.java
  src/test/java/com/jobits/dsm/benecia/domain/training/domain/TraningRepositoryTest.java
Labels: enhancement

#136 Token Builder 에러 수정
  src/main/java/com/jobits/dsm/benecia/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/jobits/dsm/benecia/infrastructure/redis/EmbeddedRedisConfig.java
  src/main/resources/application.yml
Labels: bug
